# Generated by Django 3.0.11 on 2020-12-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='private',
            field=models.BooleanField(),
        ),
    ]
