# Generated by Django 3.0.11 on 2020-12-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201213_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postu',
        ),
    ]
